# Change these first
owner: yarichltd # Your GitHub organization or username
repo: fugapediastatus # Your GitHub repository name

# Add your sites here
sites:
  - name: Fugapedia Core
    url: https://fugapedia.xyz
    icon: https://fugapedia.xyz/favicon.ico
  - name: Fugapedia Wiki
    url: https://wiki.fugapedia.xyz
    icon: https://fugapedia.xyz/favicon.ico
  - name: Fugapedia Books
    url: https://books.fugapedia.xyz
    icon: https://fugapedia.xyz/favicon.ico
  - name: Fugapedia Books (Old)
    url: https://fugapedia.xyz/ebooks/
    icon: https://fugapedia.xyz/favicon.ico

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: status.fugapedia.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /fugapediastatus
  logoUrl: https://fugapedia.xyz/images/onlyFUGAPEDIA.png
  name: Статус сети
  introTitle: ""
  introMessage: Независимый статус сети в **реальном времени**, работающий на [открытом репозитории](https://github.com/upptime/upptime). 
  navbar:
    - title: Назад 
      href: https://fugapedia.xyz/menu.html
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
